version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    build: ./db
    environment:
      MYSQL_DATABASE: banking
      MYSQL_USER: root
      MYSQL_PASSWORD: Lambda471471$#

    ports:
      - "3306:3306"
