version: '3'
services:
  app:
    build: banking-application
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    build: banking-image
    environment:
      MYSQL_DATABASE: banking
      MYSQL_USER: root
      MYSQL_PASSWORD: Lambda471471$#

    ports:
      - "3306:3306"
